from . import material_requisition
from . import material_requisition_line
from . import material_requisition_approval
from . import stock_location
from . import stock_picking
from . import stock_move
from . import purchase_order
from . import purchase_order_line
from . import res_users
from . import hr_employee
